// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/api/proto/get/get.proto

package get

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityName    string                 `protobuf:"bytes,1,opt,name=EntityName,proto3" json:"EntityName,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	GetType       string                 `protobuf:"bytes,3,opt,name=GetType,proto3" json:"GetType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pkg_api_proto_get_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_get_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_get_get_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *GetRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *GetRequest) GetGetType() string {
	if x != nil {
		return x.GetType
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_api_proto_get_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_get_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_get_get_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []string               `protobuf:"bytes,1,rep,name=Entities,proto3" json:"Entities,omitempty"`
	Response      *Response              `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pkg_api_proto_get_get_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_get_get_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_get_get_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *GetResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetRealTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityName    string                 `protobuf:"bytes,1,opt,name=EntityName,proto3" json:"EntityName,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealTimeRequest) Reset() {
	*x = GetRealTimeRequest{}
	mi := &file_pkg_api_proto_get_get_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealTimeRequest) ProtoMessage() {}

func (x *GetRealTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_get_get_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealTimeRequest.ProtoReflect.Descriptor instead.
func (*GetRealTimeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_get_get_proto_rawDescGZIP(), []int{3}
}

func (x *GetRealTimeRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *GetRealTimeRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_pkg_api_proto_get_get_proto protoreflect.FileDescriptor

const file_pkg_api_proto_get_get_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/api/proto/get/get.proto\"`\n" +
	"\n" +
	"GetRequest\x12\x1e\n" +
	"\n" +
	"EntityName\x18\x01 \x01(\tR\n" +
	"EntityName\x12\x18\n" +
	"\aPayload\x18\x02 \x01(\tR\aPayload\x12\x18\n" +
	"\aGetType\x18\x03 \x01(\tR\aGetType\"0\n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"P\n" +
	"\vGetResponse\x12\x1a\n" +
	"\bEntities\x18\x01 \x03(\tR\bEntities\x12%\n" +
	"\bresponse\x18\x02 \x01(\v2\t.ResponseR\bresponse\"N\n" +
	"\x12GetRealTimeRequest\x12\x1e\n" +
	"\n" +
	"EntityName\x18\x01 \x01(\tR\n" +
	"EntityName\x12\x18\n" +
	"\aPayload\x18\x02 \x01(\tR\aPayload2b\n" +
	"\n" +
	"GetService\x12 \n" +
	"\x03Get\x12\v.GetRequest\x1a\f.GetResponse\x122\n" +
	"\vGetRealTime\x12\x13.GetRealTimeRequest\x1a\f.GetResponse0\x01B\x14Z\x12./pkg/protobuf/getb\x06proto3"

var (
	file_pkg_api_proto_get_get_proto_rawDescOnce sync.Once
	file_pkg_api_proto_get_get_proto_rawDescData []byte
)

func file_pkg_api_proto_get_get_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_get_get_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_get_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_get_get_proto_rawDesc), len(file_pkg_api_proto_get_get_proto_rawDesc)))
	})
	return file_pkg_api_proto_get_get_proto_rawDescData
}

var file_pkg_api_proto_get_get_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_proto_get_get_proto_goTypes = []any{
	(*GetRequest)(nil),         // 0: GetRequest
	(*Response)(nil),           // 1: Response
	(*GetResponse)(nil),        // 2: GetResponse
	(*GetRealTimeRequest)(nil), // 3: GetRealTimeRequest
}
var file_pkg_api_proto_get_get_proto_depIdxs = []int32{
	1, // 0: GetResponse.response:type_name -> Response
	0, // 1: GetService.Get:input_type -> GetRequest
	3, // 2: GetService.GetRealTime:input_type -> GetRealTimeRequest
	2, // 3: GetService.Get:output_type -> GetResponse
	2, // 4: GetService.GetRealTime:output_type -> GetResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_get_get_proto_init() }
func file_pkg_api_proto_get_get_proto_init() {
	if File_pkg_api_proto_get_get_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_get_get_proto_rawDesc), len(file_pkg_api_proto_get_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_get_get_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_get_get_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_get_get_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_get_get_proto = out.File
	file_pkg_api_proto_get_get_proto_goTypes = nil
	file_pkg_api_proto_get_get_proto_depIdxs = nil
}
