// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/api/proto/poll/poll.proto

package poll

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PollId        string                 `protobuf:"bytes,2,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"` // uuid как строка
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Procent       float32                `protobuf:"fixed32,4,opt,name=procent,proto3" json:"procent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_poll_poll_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Field) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *Field) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Field) GetProcent() float32 {
	if x != nil {
		return x.Procent
	}
	return 0
}

// Аналог структуры Poll из Go
type Poll struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid как строка
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AuthorId       string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Desc           string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Fields         []*Field               `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	LimitedForTime bool                   `protobuf:"varint,6,opt,name=limited_for_time,json=limitedForTime,proto3" json:"limited_for_time,omitempty"`
	DeleteIn       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=delete_in,json=deleteIn,proto3" json:"delete_in,omitempty"`
	Closed         bool                   `protobuf:"varint,8,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Poll) Reset() {
	*x = Poll{}
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poll.ProtoReflect.Descriptor instead.
func (*Poll) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_poll_poll_proto_rawDescGZIP(), []int{1}
}

func (x *Poll) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Poll) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Poll) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Poll) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Poll) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Poll) GetLimitedForTime() bool {
	if x != nil {
		return x.LimitedForTime
	}
	return false
}

func (x *Poll) GetDeleteIn() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteIn
	}
	return nil
}

func (x *Poll) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type RequestGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGet) Reset() {
	*x = RequestGet{}
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGet) ProtoMessage() {}

func (x *RequestGet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGet.ProtoReflect.Descriptor instead.
func (*RequestGet) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_poll_poll_proto_rawDescGZIP(), []int{2}
}

func (x *RequestGet) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type RequestUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUpdate) Reset() {
	*x = RequestUpdate{}
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdate) ProtoMessage() {}

func (x *RequestUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdate.ProtoReflect.Descriptor instead.
func (*RequestUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_poll_poll_proto_rawDescGZIP(), []int{3}
}

func (x *RequestUpdate) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RequestUpdate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequestUpdate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_poll_poll_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RequestDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDelete) Reset() {
	*x = RequestDelete{}
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDelete) ProtoMessage() {}

func (x *RequestDelete) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDelete.ProtoReflect.Descriptor instead.
func (*RequestDelete) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_poll_poll_proto_rawDescGZIP(), []int{5}
}

func (x *RequestDelete) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type RequestCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *Poll                  `protobuf:"bytes,1,opt,name=Form,proto3" json:"Form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCreate) Reset() {
	*x = RequestCreate{}
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreate) ProtoMessage() {}

func (x *RequestCreate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreate.ProtoReflect.Descriptor instead.
func (*RequestCreate) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_poll_poll_proto_rawDescGZIP(), []int{6}
}

func (x *RequestCreate) GetForm() *Poll {
	if x != nil {
		return x.Form
	}
	return nil
}

type RequestGetMore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetMore) Reset() {
	*x = RequestGetMore{}
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetMore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetMore) ProtoMessage() {}

func (x *RequestGetMore) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetMore.ProtoReflect.Descriptor instead.
func (*RequestGetMore) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_poll_poll_proto_rawDescGZIP(), []int{7}
}

func (x *RequestGetMore) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequestGetMore) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	Poll          *Poll                  `protobuf:"bytes,2,opt,name=Poll,proto3" json:"Poll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_poll_poll_proto_rawDescGZIP(), []int{8}
}

func (x *GetResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetResponse) GetPoll() *Poll {
	if x != nil {
		return x.Poll
	}
	return nil
}

type GetMoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	Forms         []*Poll                `protobuf:"bytes,2,rep,name=Forms,proto3" json:"Forms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoreResponse) Reset() {
	*x = GetMoreResponse{}
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoreResponse) ProtoMessage() {}

func (x *GetMoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_poll_poll_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoreResponse.ProtoReflect.Descriptor instead.
func (*GetMoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_poll_poll_proto_rawDescGZIP(), []int{9}
}

func (x *GetMoreResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetMoreResponse) GetForms() []*Poll {
	if x != nil {
		return x.Forms
	}
	return nil
}

var File_pkg_api_proto_poll_poll_proto protoreflect.FileDescriptor

const file_pkg_api_proto_poll_poll_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/api/proto/poll/poll.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\x05Field\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\apoll_id\x18\x02 \x01(\tR\x06pollId\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x18\n" +
	"\aprocent\x18\x04 \x01(\x02R\aprocent\"\x9d\x02\n" +
	"\x04Poll\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x1e\n" +
	"\x06fields\x18\x05 \x03(\v2\x06.FieldR\x06fields\x12(\n" +
	"\x10limited_for_time\x18\x06 \x01(\bR\x0elimitedForTime\x127\n" +
	"\tdelete_in\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bdeleteIn\x12\x16\n" +
	"\x06closed\x18\b \x01(\bR\x06closed\"\x1c\n" +
	"\n" +
	"RequestGet\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"G\n" +
	"\rRequestUpdate\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\tR\x05Value\"0\n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"\x1f\n" +
	"\rRequestDelete\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"*\n" +
	"\rRequestCreate\x12\x19\n" +
	"\x04Form\x18\x01 \x01(\v2\x05.PollR\x04Form\"8\n" +
	"\x0eRequestGetMore\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"O\n" +
	"\vGetResponse\x12%\n" +
	"\bResponse\x18\x01 \x01(\v2\t.ResponseR\bResponse\x12\x19\n" +
	"\x04Poll\x18\x02 \x01(\v2\x05.PollR\x04Poll\"U\n" +
	"\x0fGetMoreResponse\x12%\n" +
	"\bResponse\x18\x01 \x01(\v2\t.ResponseR\bResponse\x12\x1b\n" +
	"\x05Forms\x18\x02 \x03(\v2\x05.PollR\x05Forms2\xcc\x01\n" +
	"\vPollService\x12 \n" +
	"\x03Get\x12\v.RequestGet\x1a\f.GetResponse\x12,\n" +
	"\aGetMore\x12\x0f.RequestGetMore\x1a\x10.GetMoreResponse\x12#\n" +
	"\x06Update\x12\x0e.RequestUpdate\x1a\t.Response\x12#\n" +
	"\x06Delete\x12\x0e.RequestDelete\x1a\t.Response\x12#\n" +
	"\x06Create\x12\x0e.RequestCreate\x1a\t.ResponseB\x19Z\x17./pkg/api/protobuf/pollb\x06proto3"

var (
	file_pkg_api_proto_poll_poll_proto_rawDescOnce sync.Once
	file_pkg_api_proto_poll_poll_proto_rawDescData []byte
)

func file_pkg_api_proto_poll_poll_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_poll_poll_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_poll_poll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_poll_poll_proto_rawDesc), len(file_pkg_api_proto_poll_poll_proto_rawDesc)))
	})
	return file_pkg_api_proto_poll_poll_proto_rawDescData
}

var file_pkg_api_proto_poll_poll_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_api_proto_poll_poll_proto_goTypes = []any{
	(*Field)(nil),                 // 0: Field
	(*Poll)(nil),                  // 1: Poll
	(*RequestGet)(nil),            // 2: RequestGet
	(*RequestUpdate)(nil),         // 3: RequestUpdate
	(*Response)(nil),              // 4: Response
	(*RequestDelete)(nil),         // 5: RequestDelete
	(*RequestCreate)(nil),         // 6: RequestCreate
	(*RequestGetMore)(nil),        // 7: RequestGetMore
	(*GetResponse)(nil),           // 8: GetResponse
	(*GetMoreResponse)(nil),       // 9: GetMoreResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_pkg_api_proto_poll_poll_proto_depIdxs = []int32{
	10, // 0: Poll.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: Poll.fields:type_name -> Field
	10, // 2: Poll.delete_in:type_name -> google.protobuf.Timestamp
	1,  // 3: RequestCreate.Form:type_name -> Poll
	4,  // 4: GetResponse.Response:type_name -> Response
	1,  // 5: GetResponse.Poll:type_name -> Poll
	4,  // 6: GetMoreResponse.Response:type_name -> Response
	1,  // 7: GetMoreResponse.Forms:type_name -> Poll
	2,  // 8: PollService.Get:input_type -> RequestGet
	7,  // 9: PollService.GetMore:input_type -> RequestGetMore
	3,  // 10: PollService.Update:input_type -> RequestUpdate
	5,  // 11: PollService.Delete:input_type -> RequestDelete
	6,  // 12: PollService.Create:input_type -> RequestCreate
	8,  // 13: PollService.Get:output_type -> GetResponse
	9,  // 14: PollService.GetMore:output_type -> GetMoreResponse
	4,  // 15: PollService.Update:output_type -> Response
	4,  // 16: PollService.Delete:output_type -> Response
	4,  // 17: PollService.Create:output_type -> Response
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_poll_poll_proto_init() }
func file_pkg_api_proto_poll_poll_proto_init() {
	if File_pkg_api_proto_poll_poll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_poll_poll_proto_rawDesc), len(file_pkg_api_proto_poll_poll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_poll_poll_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_poll_poll_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_poll_poll_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_poll_poll_proto = out.File
	file_pkg_api_proto_poll_poll_proto_goTypes = nil
	file_pkg_api_proto_poll_poll_proto_depIdxs = nil
}
